global:
  scrape_interval: 10s

scrape_configs:
  - job_name: 'prometheus_master'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:9090']
  - job_name: 'kafka_lag_exporter'
    scrape_interval: 5s
    static_configs:
      - targets: ['kafka-lag-exporter:9208']
