- name: Deploy Prometheus
  gather_facts: No
  hosts: centosdocker

  handlers:
    - name: restart_prometheus_container
      docker_container:
        name: prometheus
        state: started
        restart: yes

  tasks:
    - name: Deploy Prometheus
      docker_container:
        name: prometheus
        image: prom/prometheus
        state: started
        ports:
          - "9090:9090"
        mounts:
          -
            type: volume
            source: "prometheus"
            target: "/etc/prometheus/"
        networks_cli_compatible: yes
        networks:
          - name: sandbox
    - name: Configure Prometheus
      copy:
        src: "prometheus.yml"
        dest: "/var/lib/docker/volumes/prometheus/_data/prometheus.yml"
      notify: restart_prometheus_container
